/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:862f51f1413151f3b6e8941b2227b271:b16ed7d81695db495f30fe3b788946eb:ab3cd46ba0cd6e85f0c09a20d37b0572$
 *
 */
namespace DevilSoup
{
	public class HandWave
	{
		public const string Hand_001 = "001";
		public const string Hand_002 = "002";
		public const string Hand_003 = "003";
		public const string Hand_004 = "004";
		public const string Hand_005 = "005";
		public const string Hand_006 = "006";
		public const string Hand_007 = "007";
		public const string Hand_008 = "008";
	}
}