/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:862f51f1413151f3b6e8941b2227b271:b16ed7d81695db495f30fe3b788946eb:ab3cd46ba0cd6e85f0c09a20d37b0572$
 *
 */
namespace DevilSoup
{
	public class Images
	{
		public const string Hand_001 = "001";
        public const int handIndexInc = 1;
        public const int handsLimit = 8;

        public const string HP_100=  "100";

        public const string Temp_200 = "200";
        public const int TempBottomLimit = 200;
        public const int TempTopLimit = 2200;
    }
}